# Generated by Django 4.1.3 on 2024-01-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_delete_tasklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='memo',
            new_name='content',
        ),
    ]
