# Generated by Django 4.1.3 on 2024-01-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_memo_todo_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='create_at',
            new_name='created',
        ),
    ]
